// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalInfo } from "./GoalInfo";
import type { NodeLeaf } from "./NodeLeaf";

export type NodeGoal = { type: "Fixpoint" } | { type: "Goal", data: GoalInfo, } | { type: "Leaf", leaf: NodeLeaf, };