// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChildRelKind } from "./ChildRelKind";
import type { NodeGoal } from "./NodeGoal";
import type { NodeIdx } from "./NodeIdx";

export interface SerializeTree { root: NodeIdx, nodes: Array<NodeGoal>, children: Record<NodeIdx, Array<NodeIdx>>, parent: Record<NodeIdx, NodeIdx>, relationship: Record<NodeIdx, Record<NodeIdx, ChildRelKind>>, }